# Generated by Django 5.0.6 on 2025-07-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_alter_actividad_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio en pesos (mxn)'),
        ),
    ]
